-- Kith schema v1 — plan/02-rest-api.md §2
-- IDs are snowflake bigints generated by the app (pkg/snowflake, #3);
-- Postgres never sequences them.

CREATE EXTENSION IF NOT EXISTS citext;

-- ── users ────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id            bigint PRIMARY KEY,
    username      text NOT NULL UNIQUE,
    discriminator smallint NOT NULL,
    email         citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ── sessions ─────────────────────────────────────────────────────────────
CREATE TABLE sessions (
    id                 bigint PRIMARY KEY,
    user_id            bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash text NOT NULL,
    expires_at         timestamptz NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_id_idx ON sessions(user_id);

-- ── guilds ───────────────────────────────────────────────────────────────
CREATE TABLE guilds (
    id         bigint PRIMARY KEY,
    name       text NOT NULL,
    owner_id   bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX guilds_owner_id_idx ON guilds(owner_id);

-- ── channels ─────────────────────────────────────────────────────────────
CREATE TABLE channels (
    id         bigint PRIMARY KEY,
    guild_id   bigint REFERENCES guilds(id) ON DELETE CASCADE, -- NULL for DMs (later)
    type       smallint NOT NULL CHECK (type IN (0, 2)),      -- 0 text, 2 voice (Discord numbering)
    name       text NOT NULL,
    position   integer NOT NULL DEFAULT 0,
    parent_id  bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX channels_guild_id_idx ON channels(guild_id);

-- ── members ──────────────────────────────────────────────────────────────
CREATE TABLE members (
    guild_id  bigint NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    user_id   bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at timestamptz NOT NULL DEFAULT now(),
    nickname  text,
    PRIMARY KEY (guild_id, user_id)
);
CREATE INDEX members_user_id_idx ON members(user_id); -- "my guilds" query

-- ── roles ────────────────────────────────────────────────────────────────
CREATE TABLE roles (
    id          bigint PRIMARY KEY,
    guild_id    bigint NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    name        text NOT NULL,
    color       integer NOT NULL DEFAULT 0,
    position    integer NOT NULL DEFAULT 0,
    permissions bigint NOT NULL DEFAULT 0, -- bitfield (06-permissions.md)
    mentionable boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX roles_guild_id_idx ON roles(guild_id);

-- ── member_roles ─────────────────────────────────────────────────────────
CREATE TABLE member_roles (
    guild_id bigint NOT NULL,
    user_id  bigint NOT NULL,
    role_id  bigint NOT NULL,
    PRIMARY KEY (guild_id, user_id, role_id),
    FOREIGN KEY (guild_id, user_id) REFERENCES members(guild_id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);
CREATE INDEX member_roles_role_id_idx ON member_roles(role_id);

-- ── channel_overwrites ───────────────────────────────────────────────────
CREATE TABLE channel_overwrites (
    channel_id  bigint NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    target_id   bigint NOT NULL,
    target_type smallint NOT NULL CHECK (target_type IN (0, 1)), -- 0 role, 1 member
    allow       bigint NOT NULL DEFAULT 0,
    deny        bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (channel_id, target_id)
);

-- ── invites ──────────────────────────────────────────────────────────────
CREATE TABLE invites (
    code       text PRIMARY KEY,
    guild_id   bigint NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    channel_id bigint NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    inviter_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    uses       integer NOT NULL DEFAULT 0,
    max_uses   integer NOT NULL DEFAULT 0, -- 0 = unlimited (Discord semantics)
    expires_at timestamptz,                -- NULL = never expires
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invites_guild_id_idx ON invites(guild_id);
CREATE INDEX invites_channel_id_idx ON invites(channel_id);
CREATE INDEX invites_inviter_id_idx ON invites(inviter_id);

-- ── messages (STOP-GAP, Phases 0–2 only) ─────────────────────────────────
-- Moves to ScyllaDB in Phase 3 (plan/03-message-store.md);
-- the migration pain is the curriculum.
CREATE TABLE messages (
    id         bigint PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    author_id  bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content    text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    edited_at  timestamptz
);
CREATE INDEX messages_channel_id_id_idx ON messages(channel_id, id DESC); -- ?before= pagination
CREATE INDEX messages_author_id_idx ON messages(author_id);
